import {expect,test} from '@playwright/test'
test.setTimeout(60_000)
for(const theme of ['jade','rosewood','happyMahjong','llm','llmAnime'])test(`${theme}: action and round messages use their proper surfaces without extra requests`,async({page})=>{
  await page.setViewportSize({width:theme==='llmAnime'?568:1280,height:theme==='llmAnime'?320:720})
  let tts=0;await page.route('**/api/local-tts/**',route=>{tts++;return route.fulfill({status:503,body:'offline'})})
  await page.goto(`/tests/e2e/fixtures/blood-flow.html?count=0&theme=${theme}`)
  await expect(page.locator('.table-loading')).toHaveCount(0,{timeout:30_000})
  await page.evaluate(()=>(window as any).__setBloodFlowBubbles('action'))
  const enabled=['llm','llmAnime'].includes(theme)
  await expect(page.locator('.llm-bubble')).toHaveCount(enabled?4:0)
  await page.evaluate(()=>{(window as any).__settleBloodFlowRanking();(window as any).__setBloodFlowBubbles('round')})
  const dialog=page.getByRole('dialog',{name:'血流最终排名'})
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('.bf-result-reaction')).toHaveCount(enabled?4:0)
  if(enabled)await expect(dialog.locator('[data-result-seat="2"] .bf-result-reaction')).toContainText('西家本局小结')
  await expect(page.locator('.llm-bubble')).toHaveCount(0)
  await page.waitForTimeout(300)
  if(theme==='llmAnime'){
    const visible=await dialog.locator('.bf-result-amount,.bf-result-reaction').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect(),body=e.closest('.bf-settlement-body')!.getBoundingClientRect();return r.top>=body.top&&r.bottom<=body.bottom}))
    expect(visible).toBe(true)
  }
  await page.screenshot({path:`test-results/blood-flow-${theme}-final-reactions.png`})
  await dialog.getByRole('button',{name:'查看牌桌',exact:true}).click()
  await expect(page.locator('.llm-bubble')).toHaveCount(enabled?4:0)
  await page.getByRole('button',{name:'返回结算',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await expect(dialog).toHaveClass(/restored/)
  expect(tts).toBe(0)
  await page.evaluate(()=>(window as any).__nextBloodFlowFixtureRound())
  await expect(page.locator('.llm-bubble')).toHaveCount(0)
})
test('the last cue remains readable before automatic settlement entry',async({page})=>{
  await page.goto('/tests/e2e/fixtures/blood-flow.html?count=0&motionScale=2')
  await expect(page.locator('.table-loading')).toHaveCount(0,{timeout:30_000})
  await page.evaluate(()=>{(window as any).__appendBloodFlowWin();(window as any).__settleBloodFlow(false)})
  await expect(page.locator('.blood-flow-cue')).toHaveCount(1)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('dialog',{name:'血流本局结算'})).toBeVisible({timeout:8000})
})
